const tilesValues = [
       {
           id: 1,
           head: 0,
           tail: 0
       }, {
           id: 2,
           head: 0,
           tail: 1
       }, {
           id: 3,
           head: 0,
           tail: 2
       }, {
           id: 4,
           head: 0,
           tail: 3
       }, {
           id: 5,
           head: 0,
           tail: 4
       }, {
           id: 6,
           head: 0,
           tail: 5
       }, {
           id: 7,
           head: 0,
           tail: 6
       }, {
           id: 8,
           head: 1,
           tail: 1
       }, {
           id: 9,
           head: 1,
           tail: 2
       }, {
           id: 10,
           head: 1,
           tail: 3
       }, {
           id: 11,
           head: 1,
           tail: 4
       }, {
           id: 12,
           head: 1,
           tail: 5
       }, {
           id: 13,
           head: 1,
           tail: 6
       }, {
           id: 14,
           head: 2,
           tail: 2
       }, {
           id: 15,
           head: 2,
           tail: 3
       }, {
           id: 16,
           head: 2,
           tail: 4
       }, {
           id: 17,
           head: 2,
           tail: 5
       }, {
           id: 18,
           head: 2,
           tail: 6
       }, {
           id: 19,
           head: 3,
           tail: 3
       }, {
           id: 20,
           head: 3,
           tail: 4
       }, {
           id: 21,
           head: 3,
           tail: 5
       }, {
           id: 22,
           head: 3,
           tail: 6
       }, {
           id: 23,
           head: 4,
           tail: 4
       }, {
           id: 24,
           head: 4,
           tail: 5
       }, {
           id: 25,
           head: 4,
           tail: 6
       }, {
           id: 26,
           head: 5,
           tail: 5
       }, {
           id: 27,
           head: 5,
           tail: 6
       }, {
           id: 28,
           head: 6,
           tail: 6
       }


]